// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animation.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AnimationData;
@class Animation_ShapeAnimation;
@class Animation_ShapeAnimation_TextAnimation;
@class Animation_ShapeAnimation_TextAnimation_LevelAnimation;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Animation_AnimationObject

typedef GPB_ENUM(Animation_AnimationObject) {
  /** Shape. */
  Animation_AnimationObject_Shape = 0,

  /** Chart. You will have a separate ChartAnimation message for this. */
  Animation_AnimationObject_Chart = 1,
};

GPBEnumDescriptor *Animation_AnimationObject_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Animation_AnimationObject_IsValidValue(int32_t value);

#pragma mark - Enum Animation_ShapeAnimation_TextAnimation_TextAnimationType

typedef GPB_ENUM(Animation_ShapeAnimation_TextAnimation_TextAnimationType) {
  /** whole box. */
  Animation_ShapeAnimation_TextAnimation_TextAnimationType_Box = 0,

  /** All Paras at the same time. */
  Animation_ShapeAnimation_TextAnimation_TextAnimationType_Para = 1,

  /** Animate every para one by one till the indicated PARA level. */
  Animation_ShapeAnimation_TextAnimation_TextAnimationType_Level = 2,
};

GPBEnumDescriptor *Animation_ShapeAnimation_TextAnimation_TextAnimationType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Animation_ShapeAnimation_TextAnimation_TextAnimationType_IsValidValue(int32_t value);

#pragma mark - AnimationRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AnimationRoot : GPBRootObject
@end

#pragma mark - Animation

typedef GPB_ENUM(Animation_FieldNumber) {
  Animation_FieldNumber_Obj = 1,
  Animation_FieldNumber_Data_p = 2,
  Animation_FieldNumber_ShapeAnim = 3,
};

@interface Animation : GPBMessage

@property(nonatomic, readwrite) Animation_AnimationObject obj;

@property(nonatomic, readwrite) BOOL hasObj;
/** Animation ID is present inside this data. */
@property(nonatomic, readwrite, strong, null_resettable) AnimationData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

/** Shape Animation */
@property(nonatomic, readwrite, strong, null_resettable) Animation_ShapeAnimation *shapeAnim;
/** Test to see if @c shapeAnim has been set. */
@property(nonatomic, readwrite) BOOL hasShapeAnim;

@end

#pragma mark - Animation_ShapeAnimation

typedef GPB_ENUM(Animation_ShapeAnimation_FieldNumber) {
  Animation_ShapeAnimation_FieldNumber_Text = 1,
  Animation_ShapeAnimation_FieldNumber_AnimShape = 2,
};

/**
 * If an animation has to be overridden for a paragraph
 * it is available inside the paragraph proto.
 **/
@interface Animation_ShapeAnimation : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Animation_ShapeAnimation_TextAnimation *text;
/** Test to see if @c text has been set. */
@property(nonatomic, readwrite) BOOL hasText;

/** Animate the attached Shape. */
@property(nonatomic, readwrite) BOOL animShape;

@property(nonatomic, readwrite) BOOL hasAnimShape;
@end

#pragma mark - Animation_ShapeAnimation_TextAnimation

typedef GPB_ENUM(Animation_ShapeAnimation_TextAnimation_FieldNumber) {
  Animation_ShapeAnimation_TextAnimation_FieldNumber_Type = 1,
  Animation_ShapeAnimation_TextAnimation_FieldNumber_Level = 2,
  Animation_ShapeAnimation_TextAnimation_FieldNumber_Reverse = 3,
};

@interface Animation_ShapeAnimation_TextAnimation : GPBMessage

@property(nonatomic, readwrite) Animation_ShapeAnimation_TextAnimation_TextAnimationType type;

@property(nonatomic, readwrite) BOOL hasType;
/** Bullet Level Animation */
@property(nonatomic, readwrite, strong, null_resettable) Animation_ShapeAnimation_TextAnimation_LevelAnimation *level;
/** Test to see if @c level has been set. */
@property(nonatomic, readwrite) BOOL hasLevel;

/** Reverse the text animation. */
@property(nonatomic, readwrite) BOOL reverse;

@property(nonatomic, readwrite) BOOL hasReverse;
@end

#pragma mark - Animation_ShapeAnimation_TextAnimation_LevelAnimation

typedef GPB_ENUM(Animation_ShapeAnimation_TextAnimation_LevelAnimation_FieldNumber) {
  Animation_ShapeAnimation_TextAnimation_LevelAnimation_FieldNumber_Num = 1,
  Animation_ShapeAnimation_TextAnimation_LevelAnimation_FieldNumber_Delay = 2,
};

@interface Animation_ShapeAnimation_TextAnimation_LevelAnimation : GPBMessage

/** Bullet Num (from 1-9). */
@property(nonatomic, readwrite) int32_t num;

@property(nonatomic, readwrite) BOOL hasNum;
/** Delay every para animation by a few seconds. */
@property(nonatomic, readwrite) float delay;

@property(nonatomic, readwrite) BOOL hasDelay;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
