// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chartline.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Chartline.pbobjc.h"
 #import "Properties.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ChartlineRoot

@implementation ChartlineRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ChartlineRoot_FileDescriptor

static GPBFileDescriptor *ChartlineRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - ChartLine

@implementation ChartLine

@dynamic hasType, type;
@dynamic hasCustom, custom;

typedef struct ChartLine__storage_ {
  uint32_t _has_storage_[1];
  ChartLine_ChartLinePropsType type;
  Properties *custom;
} ChartLine__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.enumDescFunc = ChartLine_ChartLinePropsType_EnumDescriptor,
        .number = ChartLine_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ChartLine__storage_, type),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasDefaultValue | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "custom",
        .dataTypeSpecific.className = GPBStringifySymbol(Properties),
        .number = ChartLine_FieldNumber_Custom,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ChartLine__storage_, custom),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ChartLine class]
                                     rootClass:[ChartlineRoot class]
                                          file:ChartlineRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ChartLine__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum ChartLine_ChartLinePropsType

GPBEnumDescriptor *ChartLine_ChartLinePropsType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Std\000Custom\000";
    static const int32_t values[] = {
        ChartLine_ChartLinePropsType_Std,
        ChartLine_ChartLinePropsType_Custom,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(ChartLine_ChartLinePropsType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:ChartLine_ChartLinePropsType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL ChartLine_ChartLinePropsType_IsValidValue(int32_t value__) {
  switch (value__) {
    case ChartLine_ChartLinePropsType_Std:
    case ChartLine_ChartLinePropsType_Custom:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
