// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: font.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Font_FontFamily;
GPB_ENUM_FWD_DECLARE(FontRef);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FontRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface FontRoot : GPBRootObject
@end

#pragma mark - Font

typedef GPB_ENUM(Font_FieldNumber) {
  Font_FieldNumber_Ref = 1,
  Font_FieldNumber_FontFamily = 2,
  Font_FieldNumber_Symbol = 3,
};

@interface Font : GPBMessage

@property(nonatomic, readwrite) enum FontRef ref;

@property(nonatomic, readwrite) BOOL hasRef;
@property(nonatomic, readwrite, strong, null_resettable) Font_FontFamily *fontFamily;
/** Test to see if @c fontFamily has been set. */
@property(nonatomic, readwrite) BOOL hasFontFamily;

/** used mainly for symbol fonts. */
@property(nonatomic, readwrite, strong, null_resettable) Font_FontFamily *symbol;
/** Test to see if @c symbol has been set. */
@property(nonatomic, readwrite) BOOL hasSymbol;

@end

#pragma mark - Font_FontFamily

typedef GPB_ENUM(Font_FontFamily_FieldNumber) {
  Font_FontFamily_FieldNumber_Name = 1,
  Font_FontFamily_FieldNumber_Charset = 2,
};

@interface Font_FontFamily : GPBMessage

/** <regex name="alphaNumeric" value="[a-zA-Z0-9]+$"/> */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

/** Char set. */
@property(nonatomic, readwrite) int32_t charset;

@property(nonatomic, readwrite) BOOL hasCharset;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
