// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linechartseries.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Linechartseries.pbobjc.h"
 #import "Seriesdetails.pbobjc.h"
 #import "Datamarker.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - LinechartseriesRoot

@implementation LinechartseriesRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - LinechartseriesRoot_FileDescriptor

static GPBFileDescriptor *LinechartseriesRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - LineChartSeries

@implementation LineChartSeries

@dynamic hasDetails, details;
@dynamic hasSmooth, smooth;
@dynamic hasMarker, marker;

typedef struct LineChartSeries__storage_ {
  uint32_t _has_storage_[1];
  SeriesDetails *details;
  DataMarker *marker;
} LineChartSeries__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "details",
        .dataTypeSpecific.className = GPBStringifySymbol(SeriesDetails),
        .number = LineChartSeries_FieldNumber_Details,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(LineChartSeries__storage_, details),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "smooth",
        .dataTypeSpecific.className = NULL,
        .number = LineChartSeries_FieldNumber_Smooth,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasDefaultValue),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "marker",
        .dataTypeSpecific.className = GPBStringifySymbol(DataMarker),
        .number = LineChartSeries_FieldNumber_Marker,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(LineChartSeries__storage_, marker),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[LineChartSeries class]
                                     rootClass:[LinechartseriesRoot class]
                                          file:LinechartseriesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(LineChartSeries__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
