// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: margin.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Margin.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MarginRoot

@implementation MarginRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MarginRoot_FileDescriptor

static GPBFileDescriptor *MarginRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - Margin

@implementation Margin

@dynamic hasLeft, left;
@dynamic hasTop, top;
@dynamic hasRight, right;
@dynamic hasBottom, bottom;

typedef struct Margin__storage_ {
  uint32_t _has_storage_[1];
  float left;
  float top;
  float right;
  float bottom;
} Margin__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "left",
        .dataTypeSpecific.className = NULL,
        .number = Margin_FieldNumber_Left,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Margin__storage_, left),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "top",
        .dataTypeSpecific.className = NULL,
        .number = Margin_FieldNumber_Top,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Margin__storage_, top),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "right",
        .dataTypeSpecific.className = NULL,
        .number = Margin_FieldNumber_Right,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Margin__storage_, right),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "bottom",
        .dataTypeSpecific.className = NULL,
        .number = Margin_FieldNumber_Bottom,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Margin__storage_, bottom),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Margin class]
                                     rootClass:[MarginRoot class]
                                          file:MarginRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Margin__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
