// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nonvisualpictureprops.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Nonvisualpictureprops.pbobjc.h"
 #import "Nonvisualpicturedrawingprops.pbobjc.h"
 #import "Nonvisualdrawingprops.pbobjc.h"
 #import "Nonvisualprops.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - NonvisualpicturepropsRoot

@implementation NonvisualpicturepropsRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - NonvisualpicturepropsRoot_FileDescriptor

static GPBFileDescriptor *NonvisualpicturepropsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - NonVisualPictureProps

@implementation NonVisualPictureProps

@dynamic hasNvDprops, nvDprops;
@dynamic hasNvOdprops, nvOdprops;
@dynamic hasNvProps, nvProps;

typedef struct NonVisualPictureProps__storage_ {
  uint32_t _has_storage_[1];
  NonVisualDrawingProps *nvDprops;
  NonVisualPictureDrawingProps *nvOdprops;
  NonVisualProps *nvProps;
} NonVisualPictureProps__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "nvDprops",
        .dataTypeSpecific.className = GPBStringifySymbol(NonVisualDrawingProps),
        .number = NonVisualPictureProps_FieldNumber_NvDprops,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NonVisualPictureProps__storage_, nvDprops),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "nvOdprops",
        .dataTypeSpecific.className = GPBStringifySymbol(NonVisualPictureDrawingProps),
        .number = NonVisualPictureProps_FieldNumber_NvOdprops,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(NonVisualPictureProps__storage_, nvOdprops),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "nvProps",
        .dataTypeSpecific.className = GPBStringifySymbol(NonVisualProps),
        .number = NonVisualPictureProps_FieldNumber_NvProps,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(NonVisualPictureProps__storage_, nvProps),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NonVisualPictureProps class]
                                     rootClass:[NonvisualpicturepropsRoot class]
                                          file:NonvisualpicturepropsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NonVisualPictureProps__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\003E\000\002\003b\004\000\003\007\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
