// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nonvisualprops.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class NonVisualProps_EmbedFile;
@class NonVisualProps_EmbedFile_TwitterData;
@class PlaceHolder;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum NonVisualProps_EmbedFile_EmbedType

typedef GPB_ENUM(NonVisualProps_EmbedFile_EmbedType) {
  NonVisualProps_EmbedFile_EmbedType_Internal = 0,
  NonVisualProps_EmbedFile_EmbedType_External = 1,
};

GPBEnumDescriptor *NonVisualProps_EmbedFile_EmbedType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NonVisualProps_EmbedFile_EmbedType_IsValidValue(int32_t value);

#pragma mark - Enum NonVisualProps_EmbedFile_EmbeddedSite

typedef GPB_ENUM(NonVisualProps_EmbedFile_EmbeddedSite) {
  NonVisualProps_EmbedFile_EmbeddedSite_Youtube = 0,
  NonVisualProps_EmbedFile_EmbeddedSite_Twitter = 1,
  NonVisualProps_EmbedFile_EmbeddedSite_Dailymotion = 2,
};

GPBEnumDescriptor *NonVisualProps_EmbedFile_EmbeddedSite_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NonVisualProps_EmbedFile_EmbeddedSite_IsValidValue(int32_t value);

#pragma mark - Enum NonVisualProps_EmbedFile_TwitterData_TwitterType

typedef GPB_ENUM(NonVisualProps_EmbedFile_TwitterData_TwitterType) {
  NonVisualProps_EmbedFile_TwitterData_TwitterType_Live = 0,
  NonVisualProps_EmbedFile_TwitterData_TwitterType_Marked = 1,
};

GPBEnumDescriptor *NonVisualProps_EmbedFile_TwitterData_TwitterType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NonVisualProps_EmbedFile_TwitterData_TwitterType_IsValidValue(int32_t value);

#pragma mark - Enum NonVisualProps_EmbedFile_TwitterData_UpdateType

/** Should we update the live tweets Automatically or Manually. */
typedef GPB_ENUM(NonVisualProps_EmbedFile_TwitterData_UpdateType) {
  NonVisualProps_EmbedFile_TwitterData_UpdateType_Manual = 0,
  NonVisualProps_EmbedFile_TwitterData_UpdateType_Automatic = 1,
};

GPBEnumDescriptor *NonVisualProps_EmbedFile_TwitterData_UpdateType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NonVisualProps_EmbedFile_TwitterData_UpdateType_IsValidValue(int32_t value);

#pragma mark - NonvisualpropsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NonvisualpropsRoot : GPBRootObject
@end

#pragma mark - NonVisualProps

typedef GPB_ENUM(NonVisualProps_FieldNumber) {
  NonVisualProps_FieldNumber_PlaceHolder = 1,
  NonVisualProps_FieldNumber_Embed = 2,
  NonVisualProps_FieldNumber_UserDrawn = 3,
};

@interface NonVisualProps : GPBMessage

/** indicates PlaceHolder type */
@property(nonatomic, readwrite, strong, null_resettable) PlaceHolder *placeHolder;
/** Test to see if @c placeHolder has been set. */
@property(nonatomic, readwrite) BOOL hasPlaceHolder;

@property(nonatomic, readwrite, strong, null_resettable) NonVisualProps_EmbedFile *embed;
/** Test to see if @c embed has been set. */
@property(nonatomic, readwrite) BOOL hasEmbed;

/** This boolean is used to indicate that this pariticular shape has been drawn by the User. Used in Layouts and Masters to differentiate the shapes in-built in them with others. */
@property(nonatomic, readwrite) BOOL userDrawn;

@property(nonatomic, readwrite) BOOL hasUserDrawn;
@end

#pragma mark - NonVisualProps_EmbedFile

typedef GPB_ENUM(NonVisualProps_EmbedFile_FieldNumber) {
  NonVisualProps_EmbedFile_FieldNumber_Type = 1,
  NonVisualProps_EmbedFile_FieldNumber_Code = 2,
  NonVisualProps_EmbedFile_FieldNumber_Site = 3,
  NonVisualProps_EmbedFile_FieldNumber_Twitter = 4,
  NonVisualProps_EmbedFile_FieldNumber_SearchKeysArray = 5,
};

@interface NonVisualProps_EmbedFile : GPBMessage

@property(nonatomic, readwrite) NonVisualProps_EmbedFile_EmbedType type;

@property(nonatomic, readwrite) BOOL hasType;
/** The code belongs to a site allowed in "allows.txt". For Twitter , this will contain "twitterfeed" (Yes , i know this is bad design , this variable was introduced way before Twitter-Feed came-in , this variable could not be eliminated). */
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;
/** Test to see if @c code has been set. */
@property(nonatomic, readwrite) BOOL hasCode;

@property(nonatomic, readwrite) NonVisualProps_EmbedFile_EmbeddedSite site;

@property(nonatomic, readwrite) BOOL hasSite;
@property(nonatomic, readwrite, strong, null_resettable) NonVisualProps_EmbedFile_TwitterData *twitter;
/** Test to see if @c twitter has been set. */
@property(nonatomic, readwrite) BOOL hasTwitter;

/** For now , this will be used to maintain the search strings for Youtube/DailyMotion Video. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *searchKeysArray;
/** The number of items in @c searchKeysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger searchKeysArray_Count;

@end

#pragma mark - NonVisualProps_EmbedFile_TwitterData

typedef GPB_ENUM(NonVisualProps_EmbedFile_TwitterData_FieldNumber) {
  NonVisualProps_EmbedFile_TwitterData_FieldNumber_Type = 1,
  NonVisualProps_EmbedFile_TwitterData_FieldNumber_KeysArray = 2,
  NonVisualProps_EmbedFile_TwitterData_FieldNumber_Update = 3,
  NonVisualProps_EmbedFile_TwitterData_FieldNumber_IdsArray = 4,
  NonVisualProps_EmbedFile_TwitterData_FieldNumber_UserId = 5,
};

@interface NonVisualProps_EmbedFile_TwitterData : GPBMessage

@property(nonatomic, readwrite) NonVisualProps_EmbedFile_TwitterData_TwitterType type;

@property(nonatomic, readwrite) BOOL hasType;
/** Hold the search strings. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *keysArray;
/** The number of items in @c keysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger keysArray_Count;

@property(nonatomic, readwrite) NonVisualProps_EmbedFile_TwitterData_UpdateType update;

@property(nonatomic, readwrite) BOOL hasUpdate;
/** For Marked this will hold the tweet-ids. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *idsArray;
/** The number of items in @c idsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger idsArray_Count;

/** Zoho Unique ID for the user who added the twitter data. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
