// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: numberreference.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Numberreference.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - NumberreferenceRoot

@implementation NumberreferenceRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - NumberreferenceRoot_FileDescriptor

static GPBFileDescriptor *NumberreferenceRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - NumberReference

@implementation NumberReference

@dynamic hasFormula, formula;
@dynamic hasNumCache, numCache;

typedef struct NumberReference__storage_ {
  uint32_t _has_storage_[1];
  NSString *formula;
  NumberReference_NumCache *numCache;
} NumberReference__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "formula",
        .dataTypeSpecific.className = NULL,
        .number = NumberReference_FieldNumber_Formula,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NumberReference__storage_, formula),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "numCache",
        .dataTypeSpecific.className = GPBStringifySymbol(NumberReference_NumCache),
        .number = NumberReference_FieldNumber_NumCache,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(NumberReference__storage_, numCache),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NumberReference class]
                                     rootClass:[NumberreferenceRoot class]
                                          file:NumberreferenceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NumberReference__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - NumberReference_NumCache

@implementation NumberReference_NumCache

@dynamic hasCode, code;
@dynamic nArray, nArray_Count;

typedef struct NumberReference_NumCache__storage_ {
  uint32_t _has_storage_[1];
  NSString *code;
  GPBFloatArray *nArray;
} NumberReference_NumCache__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.className = NULL,
        .number = NumberReference_NumCache_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NumberReference_NumCache__storage_, code),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "nArray",
        .dataTypeSpecific.className = NULL,
        .number = NumberReference_NumCache_FieldNumber_NArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(NumberReference_NumCache__storage_, nArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeFloat,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NumberReference_NumCache class]
                                     rootClass:[NumberreferenceRoot class]
                                          file:NumberreferenceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NumberReference_NumCache__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    [localDescriptor setupContainingMessageClassName:GPBStringifySymbol(NumberReference)];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
