// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: piechartdetails.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Piechartdetails.pbobjc.h"
 #import "Seriesdetails.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PiechartdetailsRoot

@implementation PiechartdetailsRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - PiechartdetailsRoot_FileDescriptor

static GPBFileDescriptor *PiechartdetailsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - PieChartDetails

@implementation PieChartDetails

@dynamic seriesArray, seriesArray_Count;

typedef struct PieChartDetails__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *seriesArray;
} PieChartDetails__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "seriesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PieChartDetails_PieChartSeries),
        .number = PieChartDetails_FieldNumber_SeriesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PieChartDetails__storage_, seriesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PieChartDetails class]
                                     rootClass:[PiechartdetailsRoot class]
                                          file:PiechartdetailsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PieChartDetails__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PieChartDetails_PieChartSeries

@implementation PieChartDetails_PieChartSeries

@dynamic hasDetails, details;
@dynamic hasExplosion, explosion;

typedef struct PieChartDetails_PieChartSeries__storage_ {
  uint32_t _has_storage_[1];
  float explosion;
  SeriesDetails *details;
} PieChartDetails_PieChartSeries__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "details",
        .dataTypeSpecific.className = GPBStringifySymbol(SeriesDetails),
        .number = PieChartDetails_PieChartSeries_FieldNumber_Details,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PieChartDetails_PieChartSeries__storage_, details),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "explosion",
        .dataTypeSpecific.className = NULL,
        .number = PieChartDetails_PieChartSeries_FieldNumber_Explosion,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PieChartDetails_PieChartSeries__storage_, explosion),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PieChartDetails_PieChartSeries class]
                                     rootClass:[PiechartdetailsRoot class]
                                          file:PiechartdetailsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PieChartDetails_PieChartSeries__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    [localDescriptor setupContainingMessageClassName:GPBStringifySymbol(PieChartDetails)];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
