// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: piechartdetails.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PieChartDetails_PieChartSeries;
@class SeriesDetails;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PiechartdetailsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PiechartdetailsRoot : GPBRootObject
@end

#pragma mark - PieChartDetails

typedef GPB_ENUM(PieChartDetails_FieldNumber) {
  PieChartDetails_FieldNumber_SeriesArray = 1,
};

@interface PieChartDetails : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PieChartDetails_PieChartSeries*> *seriesArray;
/** The number of items in @c seriesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger seriesArray_Count;

@end

#pragma mark - PieChartDetails_PieChartSeries

typedef GPB_ENUM(PieChartDetails_PieChartSeries_FieldNumber) {
  PieChartDetails_PieChartSeries_FieldNumber_Details = 1,
  PieChartDetails_PieChartSeries_FieldNumber_Explosion = 2,
};

@interface PieChartDetails_PieChartSeries : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SeriesDetails *details;
/** Test to see if @c details has been set. */
@property(nonatomic, readwrite) BOOL hasDetails;

/** Distance the data point should be moved from the center of the pie. */
@property(nonatomic, readwrite) float explosion;

@property(nonatomic, readwrite) BOOL hasExplosion;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
