// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: build/protofielddefinition.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Protofielddefinition.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ProtofielddefinitionRoot

@implementation ProtofielddefinitionRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - ProtofielddefinitionRoot_FileDescriptor

static GPBFileDescriptor *ProtofielddefinitionRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.build"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - ProtoFieldDefinition

@implementation ProtoFieldDefinition

@dynamic hasName, name;
@dynamic hasRule, rule;
@dynamic hasType, type;
@dynamic hasNumber, number;
@dynamic valuesArray, valuesArray_Count;
@dynamic hasMessageName, messageName;

typedef struct ProtoFieldDefinition__storage_ {
  uint32_t _has_storage_[1];
  int32_t number;
  NSString *name;
  NSString *rule;
  NSString *type;
  NSMutableArray *valuesArray;
  NSString *messageName;
} ProtoFieldDefinition__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = ProtoFieldDefinition_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ProtoFieldDefinition__storage_, name),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "rule",
        .dataTypeSpecific.className = NULL,
        .number = ProtoFieldDefinition_FieldNumber_Rule,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ProtoFieldDefinition__storage_, rule),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = ProtoFieldDefinition_FieldNumber_Type,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ProtoFieldDefinition__storage_, type),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "number",
        .dataTypeSpecific.className = NULL,
        .number = ProtoFieldDefinition_FieldNumber_Number,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ProtoFieldDefinition__storage_, number),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "valuesArray",
        .dataTypeSpecific.className = NULL,
        .number = ProtoFieldDefinition_FieldNumber_ValuesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ProtoFieldDefinition__storage_, valuesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageName",
        .dataTypeSpecific.className = NULL,
        .number = ProtoFieldDefinition_FieldNumber_MessageName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ProtoFieldDefinition__storage_, messageName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ProtoFieldDefinition class]
                                     rootClass:[ProtofielddefinitionRoot class]
                                          file:ProtofielddefinitionRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ProtoFieldDefinition__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\006\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
