// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: build/protofielddefinition.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProtofielddefinitionRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProtofielddefinitionRoot : GPBRootObject
@end

#pragma mark - ProtoFieldDefinition

typedef GPB_ENUM(ProtoFieldDefinition_FieldNumber) {
  ProtoFieldDefinition_FieldNumber_Name = 1,
  ProtoFieldDefinition_FieldNumber_Rule = 2,
  ProtoFieldDefinition_FieldNumber_Type = 3,
  ProtoFieldDefinition_FieldNumber_Number = 4,
  ProtoFieldDefinition_FieldNumber_ValuesArray = 5,
  ProtoFieldDefinition_FieldNumber_MessageName = 6,
};

@interface ProtoFieldDefinition : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rule;
/** Test to see if @c rule has been set. */
@property(nonatomic, readwrite) BOOL hasRule;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;
/** Test to see if @c type has been set. */
@property(nonatomic, readwrite) BOOL hasType;

@property(nonatomic, readwrite) int32_t number;

@property(nonatomic, readwrite) BOOL hasNumber;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *valuesArray;
/** The number of items in @c valuesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger valuesArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageName;
/** Test to see if @c messageName has been set. */
@property(nonatomic, readwrite) BOOL hasMessageName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
