// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: textfield.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Textfield.pbobjc.h"
 #import "Datetimefield.pbobjc.h"
 #import "Slidenumberfield.pbobjc.h"
 #import "Parastyle.pbobjc.h"
 #import "Portionprops.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - TextfieldRoot

@implementation TextfieldRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - TextfieldRoot_FileDescriptor

static GPBFileDescriptor *TextfieldRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - TextField

@implementation TextField

@dynamic hasType, type;
@dynamic hasDatetime, datetime;
@dynamic hasSlidenum, slidenum;

typedef struct TextField__storage_ {
  uint32_t _has_storage_[1];
  TextField_FieldType type;
  DateTimeField datetime;
  SlideNumberField slidenum;
} TextField__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescriptionWithDefault fields[] = {
      {
        .defaultValue.valueEnum = TextField_FieldType_Datetime,
        .core.name = "type",
        .core.dataTypeSpecific.enumDescFunc = TextField_FieldType_EnumDescriptor,
        .core.number = TextField_FieldNumber_Type,
        .core.hasIndex = 0,
        .core.offset = (uint32_t)offsetof(TextField__storage_, type),
        .core.flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldHasEnumDescriptor),
        .core.dataType = GPBDataTypeEnum,
      },
      {
        .defaultValue.valueEnum = DateTimeField_Format1,
        .core.name = "datetime",
        .core.dataTypeSpecific.enumDescFunc = DateTimeField_EnumDescriptor,
        .core.number = TextField_FieldNumber_Datetime,
        .core.hasIndex = 1,
        .core.offset = (uint32_t)offsetof(TextField__storage_, datetime),
        .core.flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .core.dataType = GPBDataTypeEnum,
      },
      {
        .defaultValue.valueEnum = SlideNumberField_Num1,
        .core.name = "slidenum",
        .core.dataTypeSpecific.enumDescFunc = SlideNumberField_EnumDescriptor,
        .core.number = TextField_FieldNumber_Slidenum,
        .core.hasIndex = 2,
        .core.offset = (uint32_t)offsetof(TextField__storage_, slidenum),
        .core.flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .core.dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TextField class]
                                     rootClass:[TextfieldRoot class]
                                          file:TextfieldRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescriptionWithDefault))
                                   storageSize:sizeof(TextField__storage_)
                                         flags:GPBDescriptorInitializationFlag_FieldsWithDefault];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum TextField_FieldType

GPBEnumDescriptor *TextField_FieldType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Datetime\000Slidenum\000";
    static const int32_t values[] = {
        TextField_FieldType_Datetime,
        TextField_FieldType_Slidenum,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(TextField_FieldType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:TextField_FieldType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL TextField_FieldType_IsValidValue(int32_t value__) {
  switch (value__) {
    case TextField_FieldType_Datetime:
    case TextField_FieldType_Slidenum:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
