// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: textbody.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Textbody.pbobjc.h"
 #import "Textboxprops.pbobjc.h"
 #import "Parastyle.pbobjc.h"
 #import "Paragraph.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - TextbodyRoot

@implementation TextbodyRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - TextbodyRoot_FileDescriptor

static GPBFileDescriptor *TextbodyRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - TextBody

@implementation TextBody

@dynamic hasProps, props;
@dynamic listStylesArray, listStylesArray_Count;
@dynamic parasArray, parasArray_Count;

typedef struct TextBody__storage_ {
  uint32_t _has_storage_[1];
  TextBoxProps *props;
  NSMutableArray *listStylesArray;
  NSMutableArray *parasArray;
} TextBody__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "props",
        .dataTypeSpecific.className = GPBStringifySymbol(TextBoxProps),
        .number = TextBody_FieldNumber_Props,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TextBody__storage_, props),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "listStylesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(ParaStyle),
        .number = TextBody_FieldNumber_ListStylesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TextBody__storage_, listStylesArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "parasArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Paragraph),
        .number = TextBody_FieldNumber_ParasArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TextBody__storage_, parasArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TextBody class]
                                     rootClass:[TextbodyRoot class]
                                          file:TextbodyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TextBody__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000listStyles\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
