// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: themereference.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FontReference;
@class Reference;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ThemereferenceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ThemereferenceRoot : GPBRootObject
@end

#pragma mark - ThemeReference

typedef GPB_ENUM(ThemeReference_FieldNumber) {
  ThemeReference_FieldNumber_FillRef = 1,
  ThemeReference_FieldNumber_StrokeRef = 2,
  ThemeReference_FieldNumber_FontRef = 3,
  ThemeReference_FieldNumber_UseBgfill = 4,
};

@interface ThemeReference : GPBMessage

/** Fill Reference , */
@property(nonatomic, readwrite, strong, null_resettable) Reference *fillRef;
/** Test to see if @c fillRef has been set. */
@property(nonatomic, readwrite) BOOL hasFillRef;

/** Stroke Reference */
@property(nonatomic, readwrite, strong, null_resettable) Reference *strokeRef;
/** Test to see if @c strokeRef has been set. */
@property(nonatomic, readwrite) BOOL hasStrokeRef;

/** Font Reference. */
@property(nonatomic, readwrite, strong, null_resettable) FontReference *fontRef;
/** Test to see if @c fontRef has been set. */
@property(nonatomic, readwrite) BOOL hasFontRef;

/** Can be Used by shapes present in the Master Slide. If useBGFill is true , fillRef denotes to Background fill. */
@property(nonatomic, readwrite) BOOL useBgfill;

@property(nonatomic, readwrite) BOOL hasUseBgfill;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
