// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: themereference.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Themereference.pbobjc.h"
 #import "Reference.pbobjc.h"
 #import "Fontreference.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ThemereferenceRoot

@implementation ThemereferenceRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ThemereferenceRoot_FileDescriptor

static GPBFileDescriptor *ThemereferenceRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - ThemeReference

@implementation ThemeReference

@dynamic hasFillRef, fillRef;
@dynamic hasStrokeRef, strokeRef;
@dynamic hasFontRef, fontRef;
@dynamic hasUseBgfill, useBgfill;

typedef struct ThemeReference__storage_ {
  uint32_t _has_storage_[1];
  Reference *fillRef;
  Reference *strokeRef;
  FontReference *fontRef;
} ThemeReference__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fillRef",
        .dataTypeSpecific.className = GPBStringifySymbol(Reference),
        .number = ThemeReference_FieldNumber_FillRef,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ThemeReference__storage_, fillRef),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "strokeRef",
        .dataTypeSpecific.className = GPBStringifySymbol(Reference),
        .number = ThemeReference_FieldNumber_StrokeRef,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ThemeReference__storage_, strokeRef),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "fontRef",
        .dataTypeSpecific.className = GPBStringifySymbol(FontReference),
        .number = ThemeReference_FieldNumber_FontRef,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ThemeReference__storage_, fontRef),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "useBgfill",
        .dataTypeSpecific.className = NULL,
        .number = ThemeReference_FieldNumber_UseBgfill,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ThemeReference class]
                                     rootClass:[ThemereferenceRoot class]
                                          file:ThemereferenceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ThemeReference__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\001\007\000\002\t\000\003\007\000\004\004b\003\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
