// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: titleelement.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Titleelement.pbobjc.h"
 #import "Manuallayout.pbobjc.h"
 #import "Charttext.pbobjc.h"
 #import "Properties.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - TitleelementRoot

@implementation TitleelementRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - TitleelementRoot_FileDescriptor

static GPBFileDescriptor *TitleelementRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.adventnet.zoho.show.slides"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - TitleElement

@implementation TitleElement

@dynamic hasLayout, layout;
@dynamic hasOverlay, overlay;
@dynamic hasProps, props;
@dynamic hasTx, tx;

typedef struct TitleElement__storage_ {
  uint32_t _has_storage_[1];
  ManualLayout *layout;
  Properties *props;
  ChartText *tx;
} TitleElement__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "layout",
        .dataTypeSpecific.className = GPBStringifySymbol(ManualLayout),
        .number = TitleElement_FieldNumber_Layout,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TitleElement__storage_, layout),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "overlay",
        .dataTypeSpecific.className = NULL,
        .number = TitleElement_FieldNumber_Overlay,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "props",
        .dataTypeSpecific.className = GPBStringifySymbol(Properties),
        .number = TitleElement_FieldNumber_Props,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(TitleElement__storage_, props),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "tx",
        .dataTypeSpecific.className = GPBStringifySymbol(ChartText),
        .number = TitleElement_FieldNumber_Tx,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(TitleElement__storage_, tx),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TitleElement class]
                                     rootClass:[TitleelementRoot class]
                                          file:TitleelementRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TitleElement__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
